version: 2

updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: ".devcontainer"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: ".devcontainer/"
    schedule:
      interval: "monthly"
