name: blds

on:
  release:
    types: [published]
  push:
    branches: [ main ]
    tags:
      - '*.*.*'
  pull_request:
    branches: [ main ]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  blds:
    strategy:
      fail-fast: true
      matrix:
        registry: ["ghcr.io"]
        container: ["cf"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        if: ${{ matrix.registry == 'ghcr.io' }}
        name: Set environment variables for ghcr.io
        run: |
          echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      -
        if: ${{ matrix.registry == 'docker.io' }}
        name: Set environment variables for docker.io
        run: |
          echo "USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ matrix.registry }}/${{ env.USERNAME }}/${{ matrix.container }}ance
          tags: |
            type=sha
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        if: ${{ matrix.registry == 'docker.io' }}
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        if: ${{ matrix.registry == 'ghcr.io' }}
        name: Login to ghcr.io registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build 
        uses: docker/build-push-action@v3
        with:
          file: .devcontainer/_${{ matrix.container }}.Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ matrix.registry }}/${{ env.USERNAME }}/${{ matrix.container }}ance:test

  test:
    needs: blds
    strategy:
      fail-fast: true
      matrix:
        registry: ["ghcr.io"]
        container: ["cf"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    container:
      image: ${{ matrix.registry }}/${{ github.actor }}/${{ matrix.container }}ance:test
      options: --user 1001
    
    steps:
    - uses: actions/checkout@v3

    -
      name: Test with pytest
      run: |
        PDGM_BACK=${{ matrix.container }} pytest -vv -rA 

  push:
    needs: test
    strategy:
      matrix:
        registry: ["ghcr.io"]
        container: ["cf"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        if: ${{ matrix.registry == 'ghcr.io' }}
        name: Set environment variables for ghcr.io
        run: |
          echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      -
        if: ${{ matrix.registry == 'docker.io' }}
        name: Set environment variables for docker.io
        run: |
          echo "USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ matrix.registry }}/${{ env.USERNAME }}/${{ matrix.container }}ance
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        if: ${{ matrix.registry == 'docker.io' }}
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        if: ${{ matrix.registry == 'ghcr.io' }}
        name: Login to ghcr.io registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        if: ${{ github.event.release }}
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: .devcontainer/_${{ matrix.container }}.Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
